name: RSS URL取得自動実行

on:
  schedule:
    - cron: '0 23 * * *'  # JSTの8:00（UTCでは23:00）に毎日実行
  workflow_dispatch:       # 手動実行も可能

jobs:
  fetch-rss:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Pythonをセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 依存パッケージをインストール
        run: |
          pip install gspread oauth2client feedparser

      - name: RSS記事を取得してスプレッドシートへ追加
        env:
          GOOGLE_SHEET_CREDENTIALS: ${{ secrets.GOOGLE_SHEET_CREDENTIALS }}
        run: |
          python get_latest_rss_urls.py
